export const data = [
  {
    id: '1',
    sourceType: 'weibo',
    sourceName: '新浪微博',
    publishTime: '2023-09-15T08:30:00Z',
    url: 'https://weibo.com/article/1',
    pics: ['https://example.com/images/weibo1.jpg', 'https://example.com/images/weibo1_2.jpg'],
    likeNum: 1567,
    commentNum: 342,
    shareNum: 89,
    readNum: 12450,
    showActions: true,
    whetherCollect: false,
    folderId: 'folder1',
    titleZh: '互联网新技术发展趋势',
    contentZh:
      '随着人工智能和大数据的快速发展，互联网技术正在进入一个全新的阶段。各大科技公司纷纷投入资源开发下一代互联网应用...',
    // contentType: '官方发布',
  },
  {
    id: '2',
    sourceType: 'wechat',
    sourceName: '微信公众号',
    publishTime: '2023-09-14T15:45:00Z',
    url: 'https://mp.weixin.qq.com/article/2',
    pics: ['https://example.com/images/wechat1.jpg'],
    likeNum: 3421,
    commentNum: 578,
    shareNum: 243,
    readNum: 28976,
    showActions: true,
    whetherCollect: true,
    folderId: 'folder2',
    titleZh: '可持续发展：企业的社会责任',
    contentZh:
      '在全球气候变化的大背景下，企业的可持续发展策略变得越来越重要。本文探讨了如何将环保理念融入企业文化...',
    contentType: '官方发布',
  },
  {
    id: '3',
    sourceType: 'zhihu',
    sourceName: '知乎',
    publishTime: '2023-09-13T10:20:00Z',
    url: 'https://zhihu.com/question/3',
    pics: [],
    likeNum: 876,
    commentNum: 234,
    shareNum: 45,
    readNum: 9876,
    showActions: true,
    whetherCollect: false,
    folderId: 'folder1',
    titleZh: '人工智能会替代程序员吗？',
    contentZh:
      '随着ChatGPT等大语言模型的出现，AI辅助编程已成为现实。但这是否意味着程序员这一职业将被完全替代？本文从技术和社会角度分析了这一问题...',
    contentType: '官方发布',
  },
  {
    id: '4',
    sourceType: 'bilibili',
    sourceName: '哔哩哔哩',
    publishTime: '2023-09-12T18:30:00Z',
    url: 'https://bilibili.com/video/4',
    pics: [
      'https://example.com/images/bilibili1.jpg',
      'https://example.com/images/bilibili1_2.jpg',
      'https://example.com/images/bilibili1_3.jpg',
    ],
    likeNum: 45678,
    commentNum: 3456,
    shareNum: 1234,
    readNum: 234567,
    showActions: true,
    whetherCollect: true,
    folderId: 'folder3',
    titleZh: '5分钟学会高效时间管理',
    contentZh:
      '时间是最宝贵的资源，本视频分享了几种实用的时间管理技巧，帮助你在繁忙的生活中找到平衡...',
    contentType: '官方发布',
  },
  {
    id: '5',
    sourceType: 'toutiao',
    sourceName: '今日头条',
    publishTime: '2023-09-11T09:15:00Z',
    url: 'https://toutiao.com/article/5',
    pics: ['https://example.com/images/toutiao1.jpg'],
    likeNum: 2345,
    commentNum: 456,
    shareNum: 123,
    readNum: 34567,
    showActions: false,
    whetherCollect: false,
    folderId: 'folder2',
    titleZh: '经济学家预测明年全球经济走势',
    contentZh:
      '多位知名经济学家近日发表了对明年全球经济的预测。尽管面临诸多挑战，大多数专家认为全球经济将保持缓慢增长...',
    contentType: '官方发布',
  },
  {
    id: '6',
    sourceType: 'douyin',
    sourceName: '抖音',
    publishTime: '2023-09-10T20:45:00Z',
    url: 'https://douyin.com/video/6',
    pics: ['https://example.com/images/douyin1.jpg'],
    likeNum: 98765,
    commentNum: 4567,
    shareNum: 2345,
    readNum: 567890,
    showActions: true,
    whetherCollect: true,
    folderId: 'folder3',
    titleZh: '一分钟教你做美味早餐',
    contentZh:
      '忙碌的早晨也能享用健康美味的早餐！这个简单的食谱只需一分钟就能学会，让你的一天从美食开始...',
    contentType: '官方发布',
  },
  {
    id: '7',
    sourceType: 'xiaohongshu',
    sourceName: '小红书',
    publishTime: '2023-09-09T14:20:00Z',
    url: 'https://xiaohongshu.com/note/7',
    pics: [
      'https://example.com/images/xiaohongshu1.jpg',
      'https://example.com/images/xiaohongshu1_2.jpg',
    ],
    likeNum: 5678,
    commentNum: 876,
    shareNum: 234,
    readNum: 45678,
    showActions: true,
    whetherCollect: false,
    folderId: 'folder4',
    titleZh: '日本旅行必去的五个小众景点',
    contentZh:
      '除了东京、大阪这些热门城市，日本还有许多鲜为人知但风景绝美的小众景点。本篇笔记分享我的私藏景点清单...',
    contentType: '官方发布',
  },
  {
    id: '8',
    sourceType: 'linkedin',
    sourceName: '领英',
    publishTime: '2023-09-08T11:30:00Z',
    url: 'https://linkedin.com/post/8',
    pics: [],
    likeNum: 1234,
    commentNum: 234,
    shareNum: 56,
    readNum: 23456,
    showActions: false,
    whetherCollect: false,
    folderId: 'folder1',
    titleZh: '职场中如何有效沟通',
    contentZh:
      '沟通是职场中最重要的软技能之一。本文分享了几种提高沟通效率的技巧，帮助你在工作中更好地表达自己的想法...',
    contentType: '官方发布',
  },
  {
    id: '9',
    sourceType: 'twitter',
    sourceName: '推特',
    publishTime: '2023-09-07T16:50:00Z',
    url: 'https://twitter.com/status/9',
    pics: ['https://example.com/images/twitter1.jpg'],
    likeNum: 4567,
    commentNum: 678,
    shareNum: 1234,
    readNum: 56789,
    showActions: true,
    whetherCollect: true,
    folderId: 'folder5',
    titleZh: '科技创新者圆桌会议观点汇总',
    contentZh:
      '今日在硅谷举行的科技创新者圆桌会议上，多位行业领袖分享了对未来科技发展的见解。以下是会议的主要观点...',
    contentType: '官方发布',
  },
  {
    id: '10',
    sourceType: 'facebook',
    sourceName: '脸书',
    publishTime: '2023-09-06T08:10:00Z',
    url: 'https://facebook.com/post/10',
    pics: [
      'https://example.com/images/facebook1.jpg',
      'https://example.com/images/facebook1_2.jpg',
    ],
    likeNum: 3456,
    commentNum: 567,
    shareNum: 123,
    readNum: 45678,
    showActions: true,
    whetherCollect: false,
    folderId: 'folder2',
    titleZh: '远程工作的五个高效习惯',
    contentZh:
      '后疫情时代，远程工作已成为常态。如何在家中保持高效工作状态？这里分享五个经过验证的习惯，帮助你提高远程工作效率...',
    contentType: '官方发布',
  },
];
